# docker-compose.yml
version: '2.2'
services:
  butler-notifier:
    image: ptarmiganlabs/butler-notifier:latest
    init: true
    container_name: butler-notifier
    restart: always
    volumes:
      # Make config file accessible outside of container
      - "./config:/nodeapp/config"
    environment:
      - "NODE_ENV=production"
    logging:
      driver: json-file